label:
- bug
- feature
- documentation
- release
- config
- refactor
- question
- data
- tests
description:
- Bugfixes in codebase when something is not working.
- New enhancements and features.
- Improvements or additions to docs.
- Indicates a new release.
- Configuration and meta-infrastructural changes.
- Code refactoring.
- Further information requested.
- Issues pertaining to data or data preparations.
- Issues related to tests.
colour:
- d73a4a
- 1B6659
- 0075ca
- 108a51
- 8ed92e
- D0EFCD
- d876e3
- FAA631
- e4e669
